export type Resource = {
  id: string;
  type: string;
  title: string;
  description: string;
  source: string;
  year: string;
  region: string;
  format: string;
  featured?: boolean;
  href?: string;
};

export const resources: Resource[] = [
  {
    id: 'morth-report-2024',
    type: 'Government report',
    title: 'Road Accidents in India: 2024',
    description: 'Official MoRTH / Transport Research Wing tables: 4,87,707 crashes, 1,77,175 deaths, 4,71,441 injuries. Over-speeding accounted for 70.3% of persons killed; two-wheelers 46.2% and pedestrians 20.6% of fatalities.',
    source: 'Ministry of Road Transport & Highways',
    year: '2026',
    region: 'National',
    format: 'Report · PDF',
    featured: true,
    href: 'https://morth.gov.in',
  },
  {
    id: 'lok-sabha-2025-edar',
    type: 'Parliamentary reply',
    title: 'Road deaths in 2025',
    description: 'Unstarred Q. 1939, answered 30 July 2026. Annexure-I: 5,13,474 crashes and 1,83,434 deaths in 2025 (+3.5% / +5.3% over 2024); 2,96,447 crashes and 1,01,139 deaths in 2026 through 27 July. Annexure-II: 48,039 pedestrian deaths in 2025.',
    source: 'Lok Sabha / MoRTH eDAR',
    year: '2026',
    region: 'National',
    format: 'Written reply · Annexure',
    featured: true,
    href: 'https://sansad.in',
  },
  {
    id: 'pib-year-end-2025',
    type: 'Press release',
    title: 'National Highways network',
    description: 'PIB Delhi 30 December 2025 (PRID 2209837). NH network 1,46,560 km; expressways 3,052 km; 4-lane-and-above 43,512 km; Rah-Veer award ₹25,000.',
    source: 'Press Information Bureau',
    year: '2025',
    region: 'National',
    format: 'Press release · PIB',
    featured: true,
    href: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2209837',
  },
  {
    id: 'pib-scrappage-cashless-2026',
    type: 'Press release',
    title: 'Vehicle scrappage & trauma cover',
    description: 'PIB Delhi 4 February 2026 (PRID 2223331). 129 Registered Vehicle Scrapping Facilities; SASCI ₹2,000 crore; Cashless Treatment Scheme 2025 covers up to ₹1.5 lakh for 7 days.',
    source: 'Press Information Bureau',
    year: '2026',
    region: 'National',
    format: 'Press release · PIB',
    href: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2223331',
  },
  {
    id: 'kaggle-indian-roads-2022-2025',
    type: 'Open dataset',
    title: 'City accident sample (20k rows)',
    description: '20,000 city-level records from Kaggle (sehaj1104): severity, weather, road type, cause, and hour-of-day. 2025 is partial (Jan–Apr). Some features are synthetic — use beside MoRTH, not instead of it.',
    source: 'Kaggle / sehaj1104',
    year: '2025',
    region: 'Eight cities',
    format: 'CSV · 20,000 rows',
    featured: true,
    href: 'https://www.kaggle.com/datasets/sehaj1104/indian-road-accident-dataset-20222025',
  },
  {
    id: 'kaggle-indian-accident-5lakh',
    type: 'Open dataset',
    title: 'Accident modelling sample (5 lakh)',
    description: '500,000-row merged Kaggle file (shivsharantripathi). Year, cause, and severity counts are nearly uniform — a modelling sample, not a MoRTH substitute. In-file casualties 12,47,304; mean risk score 62 (0–100).',
    source: 'Kaggle / shivsharantripathi',
    year: '2026',
    region: 'National sample',
    format: 'XLSX · 5,00,000 rows',
    featured: true,
    href: 'https://www.kaggle.com/datasets/shivsharantripathi/indian-accident-dataset-5lakh',
  },
  {
    id: 'who-gsrrs-2023',
    type: 'Global status report',
    title: 'WHO road safety status, 2023',
    description: 'Latest WHO global edition for the UN Decade of Action 2021–2030. About 1.16 million people are killed on the world’s roads each year; more than half are pedestrians, cyclists and motorcyclists.',
    source: 'World Health Organization',
    year: '2023',
    region: 'Global',
    format: 'Report · PDF',
    href: 'https://www.who.int/publications/i/item/9789240086517',
  },
  {
    id: 'irf-wrs-2025',
    type: 'International comparison',
    title: 'World Road Statistics 2025',
    description: 'IRF comparison cited in the MoRTH 2024 report. India ranks second after the United States in injury accidents among reporting countries.',
    source: 'International Road Federation',
    year: '2025',
    region: 'Global',
    format: 'Statistical yearbook',
    href: 'https://www.irf.global',
  },
  {
    id: 'black-corridors-nh',
    type: 'Parliamentary note',
    title: 'NH black corridors',
    description: 'MoRTH identified 6,358 continuous high-crash NH stretches during 2023–25. Tamil Nadu recorded the most; Viluppuram district had 70 such corridors.',
    source: 'Rajya Sabha / MoRTH',
    year: '2026',
    region: 'National Highways',
    format: 'Reply · note',
    href: 'https://morth.gov.in',
  },
  {
    id: 'speed-management-2024',
    type: 'Briefing note',
    title: 'Speed management on urban arterial roads',
    description: 'A practical evidence review of lower urban speed limits, street design, and enforcement in Indian cities.',
    source: 'BARS Evidence Unit',
    year: '2024',
    region: 'National',
    format: 'Briefing note',
  },
  {
    id: 'blackspot-karnataka',
    type: 'Field report',
    title: 'From black spots to safer corridors: Karnataka',
    description: 'How engineering, enforcement, and community reporting are being aligned on high-risk Karnataka stretches. Practice note — not a MoRTH annexure substitute.',
    source: 'Karnataka Road Safety Authority',
    year: '2023',
    region: 'Karnataka',
    format: 'Field note',
  },
  {
    id: 'ambulance-response',
    type: 'Briefing note',
    title: 'The first 60 minutes: emergency response times',
    description: 'Practice note on golden-hour trauma access along national corridors, read beside the NHA cashless treatment scheme (up to ₹1.5 lakh / 7 days).',
    source: 'BARS Evidence Unit',
    year: '2024',
    region: 'National',
    format: 'Briefing note',
  },
  {
    id: 'school-zones',
    type: 'Toolkit',
    title: 'Safer journeys to school',
    description: 'A co-designed toolkit for school leaders, ward officers, parents, and young road users.',
    source: 'Samaaj Practice Group',
    year: '2022',
    region: 'Maharashtra',
    format: 'Toolkit',
  },
  {
    id: 'fleet-safety',
    type: 'Case study',
    title: 'Making safety a fleet decision',
    description: 'How commercial fleets can move from one-off compliance training to leading indicators. Practice note from the Bazaar working group.',
    source: 'Bazaar Working Group',
    year: '2024',
    region: 'Telangana',
    format: 'Case study',
  },
  {
    id: 'motorcycle-helmets',
    type: 'Research paper',
    title: 'Helmet use, fit, and enforcement in tier-two cities',
    description: 'Mixed-method research from four cities on why helmet use persists, slips, and changes.',
    source: 'Indian Institute of Public Health',
    year: '2021',
    region: 'Rajasthan',
    format: 'Research note',
  },
  {
    id: 'safe-system-primer',
    type: 'Primer',
    title: 'A Safe System primer for Indian practitioners',
    description: 'A shared language for designing roads that account for human error and protect human life.',
    source: 'BARS Learning Lab',
    year: '2024',
    region: 'National',
    format: 'Primer',
  },
];

export const states = [
  { name: 'Punjab', short: 'PB', fatality: 3062, trend: -36, coverage: 71, tone: 'leading' },
  { name: 'Karnataka', short: 'KA', fatality: 12146, trend: -2, coverage: 76, tone: 'steady' },
  { name: 'Telangana', short: 'TS', fatality: 7566, trend: -5, coverage: 74, tone: 'steady' },
  { name: 'Maharashtra', short: 'MH', fatality: 16756, trend: 7, coverage: 69, tone: 'watch' },
  { name: 'Uttar Pradesh', short: 'UP', fatality: 27550, trend: 14, coverage: 48, tone: 'watch' },
];

export const directoryRecords = [
  { id: 'r-bars', kind: 'Organisation', name: 'Bharat Association of Road Safety Volunteers', detail: 'Neutral national platform · Sarkaar–Bazaar–Samaaj integrator', location: 'New Friends Colony, New Delhi', network: 'Samaaj', verified: true, initials: 'BA' },
  { id: 'r-rsp', kind: 'Expert', name: 'Rama Shankar Pandey', detail: 'Chairman, BARS', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'RP' },
  { id: 'r-uma', kind: 'Expert', name: 'Sh. V. Umashankar', detail: 'Secretary, Ministry of Road Transport & Highways', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'VU' },
  { id: 'r-belin', kind: 'Expert', name: 'Dr. Mats-Åke Belin', detail: 'Global Lead, Decade of Action for Road Safety, WHO', location: 'Geneva / Global', network: 'Samaaj', verified: true, initials: 'MB' },
  { id: 'r-pawan', kind: 'Expert', name: 'Pawan Mulukutla', detail: 'Integrated Transport, Clean Air and Hydrogen · WRI India', location: 'Bengaluru, Karnataka', network: 'Samaaj', verified: true, initials: 'PM' },
  { id: 'r-sudhir', kind: 'Expert', name: 'Sudhir Malhotra', detail: 'Former Vice-President, Renault India', location: 'New Delhi, Delhi', network: 'Bazaar', verified: true, initials: 'SM' },
  { id: 'r-naresh', kind: 'Expert', name: 'Naresh Raghavan', detail: 'Driver education · Topdriver India', location: 'India', network: 'Bazaar', verified: true, initials: 'NR' },
  { id: 'r-wri', kind: 'Organisation', name: 'WRI India', detail: 'Knowledge partner · New Delhi Road Safety Declaration', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'WR' },
  { id: 'r-who', kind: 'Organisation', name: 'World Health Organization', detail: 'Global Status Report on Road Safety · Decade of Action', location: 'New Delhi / Geneva', network: 'Samaaj', verified: true, initials: 'WH' },
  { id: 'r-morth', kind: 'Organisation', name: 'Ministry of Road Transport & Highways', detail: 'Road Accidents in India · eDAR', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'MO' },
  { id: 'r-nhai', kind: 'Organisation', name: 'National Highways Authority of India', detail: 'NH network · black corridors', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'NH' },
  { id: 'r-nha', kind: 'Organisation', name: 'National Health Authority', detail: 'Cashless Treatment Scheme · TMS 2.0', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'NA' },
  { id: 'r1', kind: 'Organisation', name: 'Karnataka Road Safety Authority', detail: 'State road safety authority', location: 'Bengaluru, Karnataka', network: 'Sarkaar', verified: true, initials: 'KR' },
  { id: 'r2', kind: 'Organisation', name: 'SaveLIFE Foundation', detail: 'Policy and emergency care', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'SL' },
  { id: 'r3', kind: 'Expert', name: 'Dr. Meera Iyer', detail: 'Trauma systems and public health', location: 'Chennai, Tamil Nadu', network: 'Samaaj', verified: true, initials: 'MI' },
  { id: 'r4', kind: 'Organisation', name: 'Mahindra Logistics', detail: 'Commercial fleet operator', location: 'Mumbai, Maharashtra', network: 'Bazaar', verified: true, initials: 'ML' },
  { id: 'r5', kind: 'Expert', name: 'Arun Prakash', detail: 'Street design and active mobility', location: 'Pune, Maharashtra', network: 'Samaaj', verified: true, initials: 'AP' },
  { id: 'r6', kind: 'Organisation', name: 'Chennai Metropolitan Transport Corporation', detail: 'Public transport operator', location: 'Chennai, Tamil Nadu', network: 'Sarkaar', verified: true, initials: 'CM' },
  { id: 'r7', kind: 'Expert', name: 'Nandita Rao', detail: 'Behaviour change and communications', location: 'Hyderabad, Telangana', network: 'Bazaar', verified: true, initials: 'ND' },
  { id: 'r8', kind: 'Organisation', name: 'Indian Institute of Technology Delhi', detail: 'Host of the National Road Safety Confluence', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'ID' },
  { id: 'r-iitb', kind: 'Organisation', name: 'Indian Institute of Technology Bombay', detail: 'Transport and urban systems research', location: 'Mumbai, Maharashtra', network: 'Samaaj', verified: true, initials: 'IB' },
  { id: 'r-topd', kind: 'Organisation', name: 'Topdriver India', detail: 'Defensive driver education', location: 'India', network: 'Bazaar', verified: true, initials: 'TD' },
  { id: 'r-renault', kind: 'Organisation', name: 'Renault India', detail: 'Industry voice on the New Delhi Declaration', location: 'Gurugram, Haryana', network: 'Bazaar', verified: true, initials: 'RI' },
  { id: 'r-sarika', kind: 'Expert', name: 'Sarika Panda Bhatt', detail: 'Street design and liveable cities', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'SP' },
  { id: 'r-geetam', kind: 'Expert', name: 'Prof. Geetam Tiwari', detail: 'Transportation research · IIT Delhi', location: 'New Delhi, Delhi', network: 'Samaaj', verified: true, initials: 'GT' },
  { id: 'r-navdeep', kind: 'Expert', name: 'Navdeep Asija, Ph.D.', detail: 'Road safety engineering', location: 'Punjab', network: 'Samaaj', verified: true, initials: 'NV' },
  { id: 'r-prerana', kind: 'Expert', name: 'Dr Prerana Arora Singh', detail: 'Road safety volunteers network', location: 'India', network: 'Samaaj', verified: true, initials: 'PA' },
  { id: 'r-giri', kind: 'Expert', name: 'Girikumar Kumaresh', detail: 'Road safety practice', location: 'India', network: 'Samaaj', verified: true, initials: 'GK' },
  { id: 'r-iiph', kind: 'Organisation', name: 'Indian Institute of Public Health', detail: 'Helmet use, trauma and public health research', location: 'Gandhinagar, Gujarat', network: 'Samaaj', verified: true, initials: 'IH' },
  { id: 'r-tnrsa', kind: 'Organisation', name: 'Tamil Nadu Road Safety Authority', detail: 'State RSA · high NH black-corridor count', location: 'Chennai, Tamil Nadu', network: 'Sarkaar', verified: true, initials: 'TN' },
  { id: 'r-up', kind: 'Organisation', name: 'Uttar Pradesh Road Safety Cell', detail: 'State cell · largest 2025 fatality count', location: 'Lucknow, Uttar Pradesh', network: 'Sarkaar', verified: true, initials: 'UP' },
  { id: 'r-mh', kind: 'Organisation', name: 'Maharashtra Road Safety Authority', detail: 'State road safety authority', location: 'Mumbai, Maharashtra', network: 'Sarkaar', verified: true, initials: 'MH' },
  { id: 'r-ts', kind: 'Organisation', name: 'Telangana Road Safety Authority', detail: 'State road safety authority', location: 'Hyderabad, Telangana', network: 'Sarkaar', verified: true, initials: 'TS' },
  { id: 'r-pb', kind: 'Organisation', name: 'Punjab Road Safety Authority', detail: 'State authority · fatality decline watch', location: 'Chandigarh, Punjab', network: 'Sarkaar', verified: true, initials: 'PB' },
  { id: 'r-kl', kind: 'Organisation', name: 'Kerala Road Safety Authority', detail: 'State road safety authority', location: 'Thiruvananthapuram, Kerala', network: 'Sarkaar', verified: true, initials: 'KL' },
  { id: 'r-gj', kind: 'Organisation', name: 'Gujarat Road Safety Authority', detail: 'State road safety authority', location: 'Gandhinagar, Gujarat', network: 'Sarkaar', verified: true, initials: 'GJ' },
  { id: 'r-rj', kind: 'Organisation', name: 'Rajasthan Road Safety Cell', detail: 'State road safety cell', location: 'Jaipur, Rajasthan', network: 'Sarkaar', verified: true, initials: 'RJ' },
  { id: 'r-wb', kind: 'Organisation', name: 'West Bengal Transport Department', detail: 'State transport and safety desk', location: 'Kolkata, West Bengal', network: 'Sarkaar', verified: true, initials: 'WB' },
  { id: 'r-dl', kind: 'Organisation', name: 'Delhi Traffic Police', detail: 'Urban enforcement and education', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'DT' },
  { id: 'r-ap', kind: 'Organisation', name: 'Andhra Pradesh Road Safety Authority', detail: 'State road safety authority', location: 'Amaravati, Andhra Pradesh', network: 'Sarkaar', verified: true, initials: 'AP' },
  { id: 'r-as', kind: 'Organisation', name: 'Assam Road Safety Cell', detail: 'State road safety cell', location: 'Guwahati, Assam', network: 'Sarkaar', verified: true, initials: 'AS' },
  { id: 'r-br', kind: 'Organisation', name: 'Bihar Road Safety Cell', detail: 'State road safety cell', location: 'Patna, Bihar', network: 'Sarkaar', verified: true, initials: 'BR' },
  { id: 'r-od', kind: 'Organisation', name: 'Odisha Road Safety Cell', detail: 'State road safety cell', location: 'Bhubaneswar, Odisha', network: 'Sarkaar', verified: true, initials: 'OD' },
  { id: 'r-mp', kind: 'Organisation', name: 'Madhya Pradesh Road Safety Authority', detail: 'State road safety authority', location: 'Bhopal, Madhya Pradesh', network: 'Sarkaar', verified: true, initials: 'MP' },
  { id: 'r-uk', kind: 'Organisation', name: 'Uttarakhand Road Safety Cell', detail: 'Hill-state road safety cell', location: 'Dehradun, Uttarakhand', network: 'Sarkaar', verified: true, initials: 'UK' },
  { id: 'r-hp', kind: 'Organisation', name: 'Himachal Pradesh Road Safety Cell', detail: 'Hill-state road safety cell', location: 'Shimla, Himachal Pradesh', network: 'Sarkaar', verified: true, initials: 'HP' },
  { id: 'r-jk', kind: 'Organisation', name: 'J&K Traffic Police', detail: 'Union territory traffic and safety', location: 'Srinagar, Jammu and Kashmir', network: 'Sarkaar', verified: true, initials: 'JK' },
  { id: 'r-mtc', kind: 'Organisation', name: 'BEST Undertaking', detail: 'Public bus operator', location: 'Mumbai, Maharashtra', network: 'Sarkaar', verified: true, initials: 'BE' },
  { id: 'r-bmtc', kind: 'Organisation', name: 'Bangalore Metropolitan Transport Corporation', detail: 'Public bus operator', location: 'Bengaluru, Karnataka', network: 'Sarkaar', verified: true, initials: 'BM' },
  { id: 'r-dtc', kind: 'Organisation', name: 'Delhi Transport Corporation', detail: 'Public bus operator', location: 'New Delhi, Delhi', network: 'Sarkaar', verified: true, initials: 'DC' },
];
